runtime: python39

automatic_scaling:
  max_instances: 1

app_engine_apis: true

env_variables:
  NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: 'True'

handlers:
- url: /webnote/
  static_files: index.html
  upload: index.html

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /webnote/FAQ\.html
  static_files: FAQ.html
  upload: FAQ\.html
- url: /webnote/hints\.html
  static_files: hints.html
  upload: hints\.html
- url: /webnote/webnote_favicon\.ico
  static_files: webnote_favicon.ico
  upload: webnote_favicon\.ico
- url: /webnote/wp-layout\.css
  static_files: wp-layout.css
  upload: wp-layout\.css
- url: /webnote/style\.css
  static_files: style.css
  upload: style\.css
- url: /webnote/objects\.js
  static_files: objects.js
  upload: objects\.js
- url: /webnote/webnote\.js
  static_files: webnote.js
  upload: webnote\.js
- url: /webnote/images
  static_dir: images

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app
